; PlatformIO Project Configuration File
; ESP32-B — Server/Controller (YoloUNO)
; ⚠️ Đã khôi phục về YoloUNO từ CONFIG_BACKUP.md

[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -DSSID_AP='"ESP32 LOCAL"'
    -DPASS_AP='12345678'

lib_deps = 
    tanakamasayuki/TensorFlowLite_ESP32@1.0.0
    adafruit/Adafruit NeoPixel@^1.15.1
    bblanchon/ArduinoJson@^6.21.3
    robtillaart/DHT20@^0.3.1
    knolleary/PubSubClient@^2.8
    DHT20
    LCD
    https://github.com/mathieucarbou/AsyncTCP.git
    https://github.com/mathieucarbou/ESPAsyncWebServer.git

lib_compat_mode = strict